"""empty message

Revision ID: 9dc5d554d73b
Revises: cc688816ce63
Create Date: 2023-11-22 15:30:41.410783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc5d554d73b'
down_revision = 'cc688816ce63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ponto_vacinacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.String(length=248), nullable=False))
        batch_op.create_unique_constraint(None, ['nome'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ponto_vacinacao', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('endereco')

    # ### end Alembic commands ###
